server:
  port: 8085

spring:
  application:
    name: "member-service"

  datasource:
    url: jdbc:mysql://localhost:3308/mediathec_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: member-service
        instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always